### ISSUE TITLE
[Panel Buttons] To change the color

### ISSUE THREAD

**Issue by tadam75** [get-focus/deprecated-focus-components-v3#42]
Hello,

We'd like the possibility to change the color of the buttons on a Panel ("Cancel" in blue and "Save" in orange for instance).

**Comment by TomGallon** [comment]
you can overload css:

![image](https://cloud.githubusercontent.com/assets/5349745/21146984/d208f5dc-c153-11e6-8660-2d24ed0dc363.png)

**Comment by GuenoleK** [comment]
Ref https://github.com/get-focus/focus-components/issues/46
