### ISSUE TITLE
[Modal] icon close visibility

### ISSUE THREAD

**Issue by aelhaoun** [get-focus/deprecated-focus-components-v3#47]
# Current behaviour

The current behaviour is that the closing icon is hidden in popin panel. which is due to it's position in the DOM.

![image](https://cloud.githubusercontent.com/assets/8221721/21136919/ef24f2be-c127-11e6-98ea-72473a2cf018.png)

# Expected behaviour

The closing icon must appear.

![image](https://cloud.githubusercontent.com/assets/8221721/21136950/0b6a87e0-c128-11e6-9972-16c8372755de.png)

**Comment by GuenoleK** [comment]
Hello @aelhaoun we have tested and we are not able to reproduce the issue.
