### ISSUE TITLE
Header not expanded does not appear after F5

### ISSUE THREAD

**Issue by aelhaoun** [get-focus/deprecated-focus-components-v3#74]
# Current behaviour

If located at the middle or bottom of the page, and press F5, the not expanded header is not appearing.

![image](https://cloud.githubusercontent.com/assets/8221721/21925420/ac5f731e-d97d-11e6-92ac-f57a9a299c86.png)

# Expected behaviour

The expected behaviour is to have the not expanded header appearing.

[If you judge it necessary, add a screenshot]
![image](https://cloud.githubusercontent.com/assets/8221721/21925388/961b800c-d97d-11e6-9270-1a7e2392b50c.png)

# Explanation of the origine of the issue

You need while initialisation, to detected in which position of the page we are located, and based on this information, decide whether to show the expanded Header or the small Header,
So var isNotFixedOrExpanded = isFixed ? false : isExpanded; is not accurate since it doesn't care about the postion of the page.

## Versions

Focus-core: v3
Focus-components: Header

**Comment by TomGallon** [comment]
reported here
https://github.com/get-focus/focus-application/issues/70
