### ISSUE TITLE
[Autocomplete] Value truncated when the label contains ':'

### ISSUE THREAD

**Issue by tadam75** [get-focus/deprecated-focus-components-v3#98]
# Current behaviour

When a label contains ':', the option displayed in the autocomplete truncates the label and only the part after the ':' is displayed.

Example : I Have a "Zone géographique" named AVANT : APRES 

![image](https://cloud.githubusercontent.com/assets/14274196/22937291/7579be1c-f2d8-11e6-9fcb-047405a146d4.png)

On my autocomplete, only the text APRES is displayed

![image](https://cloud.githubusercontent.com/assets/14274196/22937323/8a601fd8-f2d8-11e6-819b-5405b86bdade.png)

# Expected behaviour

I want the complete label to be displayed.

**Comment by GuenoleK** [comment]
@tadamK as I told you yesterday, it's a name space separator problem which can be edited on the i18next initialization. I will give suggest something in focus-application.

Thanks for the report
